import { create } from 'zustand'

export const useGameStore = create((set) => ({
  currentScreen: 'login',
  previousScreen: 'main',
  isPaused: false,
  setCurrentScreen: (screen) => set({ currentScreen: screen }),
  setPreviousScreen: (screen) => set({ previousScreen: screen }),
  setIsPaused: (value) => set({ isPaused: value }),

  playerId: null,
  userType: 'general',
  setPlayerId: (id) => set({ playerId: id }),
  setUserType: (type) => set({ userType: type }),

  playerProfile: null,
  selectedAdvisor: null,
  currentSlot: null,
  setPlayerProfile: (profile) => set({ playerProfile: profile }),
  setSelectedAdvisor: (advisor) => set({ selectedAdvisor: advisor }),
  setCurrentSlot: (slot) => set({ currentSlot: slot }),

  floor: 1,
  isGameOver: false,
  isClear: false,
  clearGrade: null,
  bankruptcyTurns: 0,
  stageTurn: 1,
  setFloor: (floor) => set({ floor }),
  setIsGameOver: (value) => set({ isGameOver: value }),
  setIsClear: (value) => set({ isClear: value }),
  setClearGrade: (grade) => set({ clearGrade: grade }),

  health: 10,
  maxHealth: 10,
  momentum: 0,
  momentumHistory: [],
  capital: 5000000,
  debt: 0,
  loans: [],
  creditScore: 70,
  quality: 8,
  cost: 3000,
  orderCap: null,
  costReductionTotal: 0,
  qualityUpgradeCount: 0,
  costReductionCount: 0,
  factoryFailStreak: 0,
  costReductionFailStreak: 0,
  brand: 2,
  awareness: 10,
  lastCapital: 5000000,

  econPhase: 'stable',
  rivals: [],
  metRivals: [],
  playerShareHistory: [],
  revenueHistory: [],
  profitHistory: [],
  capitalHistory: [],
  lastTotalDemand: 1000,
  activeEffects: [],
  currentExternalEvent: null,
  currentInternalEvent: null,
  currentRivalEvent: null,
  pendingNextFloor: null,
  monopolEvaluation: null,
  factoryActionThisTurn: null,
  lastSettlementResult: null,

  rivalCapital: 0,
  rivalInitialCapital: 0,
  rivalConsecutiveLoss: 0,
  rivalNetProfit: 0,
  rivalBankrupt: false,
  currentStageId: 'stage_1',
  stageFailCount: 0,
  rivalPrice: 10000,
  rivalCost: 3000,
  rivalQuality: 8,
  rivalOrderAmount: 0,
  rivalActualSales: 0,

  bossShareHistory: [],
  bossCounterActive: false,
  bossClearConditionMet: false,
  bossLastPlayerStrategy: null,

  stats: {
    playtime: 0,
    profitTurns: 0,
    lossTurns: 0,
    maxShare: 0,
    bankruptcyCount: 0,
    externalEventCount: 0,
    rivalEventCount: 0,
    eventSuccessCount: 0,
    eventTotalCount: 0,
    rivalDominated: 0,
    profitStreak: 0,
    shareFirstStreak: 0,
    dictionaryViewCount: 0,
    dictionaryAllViewed: false,
    dictionaryViewedTerms: [],
  },

  unlockedAchievements: [],
  newAchievements: [],
  aiMessages: [],

  currentStrategy: {
    price: null,
    orderAmount: null,
    marketingBudget: 0,
    factoryAction: null,
    loanAction: null,
  },

  completedTutorials: [],

  settings: {
    language: 'ko',
    masterVolume: 50,
    bgmVolume: 100,
    sfxVolume: 100,
    bgmOn: true,
    sfxOn: true,
    background: true,
    screenShake: true,
    marketingLimitMode: 'ratio',
    tutorial: true,
    economyHint: true,
    strategyWarning: true,
    autoSaveAlert: true,
  },

  setSettings: (settings) => set({ settings }),
  updateSetting: (key, value) => set(state => ({
    settings: { ...state.settings, [key]: value },
  })),
  setCurrentStrategy: (strategy) => set(state => ({
    currentStrategy: { ...state.currentStrategy, ...strategy },
  })),
  setFactoryAction: (action) => set({ factoryActionThisTurn: action }),
  clearFactoryAction: () => set({ factoryActionThisTurn: null }),
  addAchievement: (ids) => set(state => ({
    unlockedAchievements: [...state.unlockedAchievements, ...ids],
  })),
  setNewAchievements: (ids) => set({ newAchievements: ids }),
  appendAiMessage: (msg) => set(state => ({
    aiMessages: [...(state.aiMessages || []), msg].slice(-20),
  })),
  clearAiMessages: () => set({ aiMessages: [] }),
  updateDictionaryCount: (count, isAll, viewedTerms = null) => set(state => ({
    stats: {
      ...(state.stats || {}),
      dictionaryViewCount: count,
      dictionaryAllViewed: isAll,
      dictionaryViewedTerms: viewedTerms || state.stats?.dictionaryViewedTerms || [],
    },
  })),
  setRivalState: (data) => set({ ...data }),
  updateBossShareHistory: (share) => set(state => ({
    bossShareHistory: [...state.bossShareHistory.slice(-2), share],
  })),

  resetGame: (advisorId, playerProfile, slotNumber) => {
    const maxHealth = advisorId === 'raider' ? 8 : 10

    set({
      floor: 1,
      isGameOver: false,
      isClear: false,
      clearGrade: null,
      bankruptcyTurns: 0,
      stageTurn: 1,
      health: maxHealth,
      maxHealth,
      momentum: 0,
      momentumHistory: [],
      capital: 5000000,
      lastCapital: 5000000,
      debt: 0,
      loans: [],
      creditScore: 70,
      quality: 8,
      cost: 3000,
      orderCap: null,
      costReductionTotal: 0,
      qualityUpgradeCount: 0,
      costReductionCount: 0,
      factoryFailStreak: 0,
      costReductionFailStreak: 0,
      brand: 2,
      awareness: 10,
      econPhase: 'stable',
      rivals: [],
      metRivals: [],
      playerShareHistory: [],
      revenueHistory: [],
      profitHistory: [],
      capitalHistory: [],
      lastTotalDemand: 1000,
      activeEffects: [],
      currentExternalEvent: null,
      currentInternalEvent: null,
      currentRivalEvent: null,
      pendingNextFloor: null,
      monopolEvaluation: null,
      factoryActionThisTurn: null,
      lastSettlementResult: null,
      rivalCapital: 0,
      rivalInitialCapital: 0,
      rivalConsecutiveLoss: 0,
      rivalNetProfit: 0,
      rivalBankrupt: false,
      currentStageId: 'stage_1',
      stageFailCount: 0,
      rivalPrice: 10000,
      rivalCost: 3000,
      rivalQuality: 8,
      rivalOrderAmount: 0,
      rivalActualSales: 0,
      bossShareHistory: [],
      bossCounterActive: false,
      bossClearConditionMet: false,
      bossLastPlayerStrategy: null,
      stats: {
        playtime: 0,
        profitTurns: 0,
        lossTurns: 0,
        maxShare: 0,
        bankruptcyCount: 0,
        externalEventCount: 0,
        rivalEventCount: 0,
        eventSuccessCount: 0,
        eventTotalCount: 0,
        rivalDominated: 0,
        profitStreak: 0,
        shareFirstStreak: 0,
        dictionaryViewCount: 0,
        dictionaryAllViewed: false,
        dictionaryViewedTerms: [],
      },
      unlockedAchievements: [],
      newAchievements: [],
      aiMessages: [],
      currentStrategy: {
        price: null,
        orderAmount: null,
        marketingBudget: 0,
        factoryAction: null,
        loanAction: null,
      },
      completedTutorials: [],
      selectedAdvisor: advisorId,
      playerProfile,
      currentSlot: slotNumber,
    })
  },
}))
