export const ACHIEVEMENTS = [
  {
    id: 'demand_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '첫 흑자',
    description: '1턴 흑자 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PROFIT_ONCE' },
    educationCode: '12경제02-01',
    educationLink: '수요와 공급',
  },
  {
    id: 'demand_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '흑자 경영인',
    description: '10턴 연속 흑자',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PROFIT_STREAK', count: 10 },
    educationCode: '12경제02-01',
    educationLink: '수요와 공급',
  },
  {
    id: 'demand_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '수요 지배자',
    description: '불황 국면에서 5턴 연속 흑자',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PROFIT_STREAK_RECESSION', count: 5 },
    educationCode: '12경제02-01',
    educationLink: '수요와 공급',
  },
  {
    id: 'price_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '가격 조정',
    description: '판매가 조정으로 점유율 상승 1회',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PRICE_SHARE_UP_ONCE' },
    educationCode: '12경제02-01',
    educationLink: '가격 탄력성',
  },
  {
    id: 'price_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '가격 전략가',
    description: '판매가 조정으로 점유율 5%↑ 3회',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PRICE_SHARE_UP_5PCT', count: 3 },
    educationCode: '12경제02-01',
    educationLink: '가격 탄력성',
  },
  {
    id: 'price_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '탄력의 달인',
    description: '불황에서 가격 전략으로 점유율 1위 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PRICE_FIRST_RECESSION' },
    educationCode: '12경제02-01',
    educationLink: '가격 탄력성',
  },
  {
    id: 'factory_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '첫 절감',
    description: '원가 절감 첫 성공',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'COST_REDUCTION_ONCE' },
    educationCode: '12경제01-03',
    educationLink: '생산과 원가',
  },
  {
    id: 'factory_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '원가 관리자',
    description: '누적 원가 절감 20% 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'COST_REDUCTION_TOTAL', value: 0.20 },
    educationCode: '12경제01-03',
    educationLink: '생산과 원가',
  },
  {
    id: 'factory_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '생산 혁신가',
    description: '누적 원가 절감 40% 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'COST_REDUCTION_TOTAL', value: 0.40 },
    educationCode: '12경제01-03',
    educationLink: '생산과 원가',
  },
  {
    id: 'quality_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '품질 투자',
    description: '품질 강화 첫 성공',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'QUALITY_UPGRADE_ONCE' },
    educationCode: '12경제02-03',
    educationLink: '제품 차별화',
  },
  {
    id: 'quality_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '품질 경영',
    description: '품질 수치 50 이상 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'QUALITY_OVER', value: 50 },
    educationCode: '12경제02-03',
    educationLink: '제품 차별화',
  },
  {
    id: 'quality_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '프리미엄 브랜드',
    description: '품질 100 이상 + 브랜드 8 이상 동시 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'QUALITY_AND_BRAND', quality: 100, brand: 8 },
    educationCode: '12경제02-03',
    educationLink: '제품 차별화',
  },
  {
    id: 'marketing_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '첫 광고',
    description: '마케팅 투자 첫 시도',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'MARKETING_ONCE' },
    educationCode: '12경제03-03',
    educationLink: '마케팅 효과',
  },
  {
    id: 'marketing_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '입소문',
    description: 'awareness 50% 이상 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'AWARENESS_OVER', value: 50 },
    educationCode: '12경제03-03',
    educationLink: '마케팅 효과',
  },
  {
    id: 'marketing_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '시장 장악',
    description: 'awareness 90% 이상 + 브랜드 8 이상 동시',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'AWARENESS_AND_BRAND', awareness: 90, brand: 8 },
    educationCode: '12경제03-03',
    educationLink: '마케팅 효과',
  },
  {
    id: 'credit_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '신용 시작',
    description: '신용등급 B 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'CREDIT_GRADE', grade: 'B' },
    educationCode: '12경제01-02',
    educationLink: '금융과 신용',
  },
  {
    id: 'credit_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '신용 우량',
    description: '신용등급 A 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'CREDIT_GRADE', grade: 'A' },
    educationCode: '12경제01-02',
    educationLink: '금융과 신용',
  },
  {
    id: 'credit_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '신용 만점',
    description: '신용점수 100점 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'CREDIT_SCORE_MAX' },
    educationCode: '12경제01-02',
    educationLink: '금융과 신용',
  },
  {
    id: 'debt_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '이자 납부',
    description: '대출 이자 제때 5회 납부',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'INTEREST_PAID', count: 5 },
    educationCode: '12경제01-02',
    educationLink: '부채 관리',
  },
  {
    id: 'debt_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '빚 청산',
    description: '대출 원금 전액 상환 1회',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'LOAN_REPAID_ONCE' },
    educationCode: '12경제01-02',
    educationLink: '부채 관리',
  },
  {
    id: 'debt_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '무차입 경영',
    description: '대출 없이 50층 이상 도달',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'NO_LOAN_FLOOR', floor: 50 },
    educationCode: '12경제01-02',
    educationLink: '부채 관리',
  },
  {
    id: 'cycle_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '경기 관찰',
    description: '경기 국면 3단계 경험',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PHASE_COUNT', count: 3 },
    educationCode: '12경제03-03',
    educationLink: '경기 순환',
  },
  {
    id: 'cycle_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '경기 분석',
    description: '경기 국면 5단계 전부 경험',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PHASE_ALL' },
    educationCode: '12경제03-03',
    educationLink: '경기 순환',
  },
  {
    id: 'cycle_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '경기 예측가',
    description: 'Analyst 어드바이저로 국면 전환 10회 예측 적중',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PHASE_PREDICT', count: 10, advisorId: 'analyst' },
    educationCode: '12경제03-03',
    educationLink: '경기 순환',
  },
  {
    id: 'recession_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '불황 생존',
    description: '불황 국면에서 흑자 1회',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PROFIT_IN_RECESSION_ONCE' },
    educationCode: '12경제03-03',
    educationLink: '경기 대응',
  },
  {
    id: 'recession_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '불황 극복',
    description: '불황 국면에서 3턴 연속 흑자',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PROFIT_STREAK_RECESSION', count: 3 },
    educationCode: '12경제03-03',
    educationLink: '경기 대응',
  },
  {
    id: 'recession_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '불황의 강자',
    description: '불황 국면에서 점유율 1위 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'SHARE_FIRST_IN_RECESSION' },
    educationCode: '12경제03-03',
    educationLink: '경기 대응',
  },
  {
    id: 'consumer_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '소비자 파악',
    description: '소비자 그룹 2종 이상 점유',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'CONSUMER_GROUP_COUNT', count: 2 },
    educationCode: '12경제02-01',
    educationLink: '소비자 행동',
  },
  {
    id: 'consumer_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '소비자 이해',
    description: '소비자 그룹 4종 모두 점유',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'CONSUMER_GROUP_ALL' },
    educationCode: '12경제02-01',
    educationLink: '소비자 행동',
  },
  {
    id: 'consumer_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '소비자 심리 전문가',
    description: '국면별 전략 변경 후 점유율 상승 5회',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PHASE_STRATEGY_ADAPT', count: 5 },
    educationCode: '12경제02-01',
    educationLink: '소비자 행동',
  },
  {
    id: 'opportunity_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '선택의 무게',
    description: '이벤트 카드 선택 10회',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'EVENT_CHOICE_COUNT', count: 10 },
    educationCode: '12경제01-01',
    educationLink: '기회비용',
  },
  {
    id: 'opportunity_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '기회비용 인식',
    description: '도박 실패 후 다음 턴 안전 선택으로 흑자 전환 3회',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'GAMBLE_FAIL_SAFE_RECOVER', count: 3 },
    educationCode: '12경제01-01',
    educationLink: '기회비용',
  },
  {
    id: 'opportunity_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '최적 선택자',
    description: '이벤트 선택 성공률 70% 이상으로 클리어',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'EVENT_SUCCESS_RATE_CLEAR', rate: 0.70 },
    educationCode: '12경제01-01',
    educationLink: '기회비용',
  },
  {
    id: 'competition_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '경쟁 시작',
    description: 'MONOPOL 라이벌 3명 이상 만나기',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'MET_RIVAL_COUNT', count: 3 },
    educationCode: '12경제02-03',
    educationLink: '시장 경쟁',
  },
  {
    id: 'competition_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '시장 경쟁자',
    description: '점유율 30% 이상 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'SHARE_OVER', value: 0.30 },
    educationCode: '12경제02-03',
    educationLink: '시장 경쟁',
  },
  {
    id: 'competition_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '시장 지배자',
    description: '점유율 50% 이상 10턴 유지',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'SHARE_OVER_SUSTAINED', value: 0.50, count: 10 },
    educationCode: '12경제02-03',
    educationLink: '시장 경쟁',
  },
  {
    id: 'profit_manage_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '손익 인식',
    description: '결과 리포트 10회 확인',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'RESULT_VIEW_COUNT', count: 10 },
    educationCode: '12경제01-03',
    educationLink: '손익 관리',
  },
  {
    id: 'profit_manage_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '흑자 유지',
    description: '20턴 연속 흑자',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PROFIT_STREAK', count: 20 },
    educationCode: '12경제01-03',
    educationLink: '손익 관리',
  },
  {
    id: 'profit_manage_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '재무 달인',
    description: '30턴 연속 흑자',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PROFIT_STREAK', count: 30 },
    educationCode: '12경제01-03',
    educationLink: '손익 관리',
  },
  {
    id: 'risk_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '위기 인식',
    description: '체력 3 이하에서 회복 1회',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'HEALTH_RECOVER_FROM_LOW', threshold: 3 },
    educationCode: '12경제01-03',
    educationLink: '리스크 관리',
  },
  {
    id: 'risk_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '위기 관리',
    description: '파산 직전 (자본 음수 3턴)에서 회복',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'BANKRUPTCY_RECOVER' },
    educationCode: '12경제01-03',
    educationLink: '리스크 관리',
  },
  {
    id: 'risk_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '리스크 제로',
    description: '체력 감소 없이 30층 이상 진행',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'NO_HEALTH_LOSS_FLOOR', floor: 30 },
    educationCode: '12경제01-03',
    educationLink: '리스크 관리',
  },
  {
    id: 'education_bronze',
    category: 'ECONOMY',
    grade: 'BRONZE',
    name: '경제 입문',
    description: '경제 용어 사전 5개 이상 열람',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'DICTIONARY_VIEW_COUNT', count: 5 },
    educationCode: '12경제01-01',
    educationLink: '종합 경제 이해',
  },
  {
    id: 'education_silver',
    category: 'ECONOMY',
    grade: 'SILVER',
    name: '경제 학습자',
    description: '경제 용어 사전 전체 열람',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'DICTIONARY_ALL' },
    educationCode: '12경제01-01',
    educationLink: '종합 경제 이해',
  },
  {
    id: 'education_gold',
    category: 'ECONOMY',
    grade: 'GOLD',
    name: '경제학자',
    description: '브론즈 학습 업적 15개 전부 달성',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'ECONOMY_BRONZE_ALL' },
    educationCode: '12경제01-01',
    educationLink: '종합 경제 이해',
  },
  {
    id: 'game_start',
    category: 'GAME',
    grade: null,
    name: '첫 걸음',
    description: '게임 첫 시작',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'GAME_START' },
  },
  {
    id: 'game_raider',
    category: 'GAME',
    grade: null,
    name: '공격적 경영',
    description: 'The Raider로 클리어',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'CLEAR_WITH_ADVISOR', advisorId: 'raider' },
  },
  {
    id: 'game_guardian',
    category: 'GAME',
    grade: null,
    name: '철벽 수비',
    description: 'The Guardian으로 클리어',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'CLEAR_WITH_ADVISOR', advisorId: 'guardian' },
  },
  {
    id: 'game_analyst',
    category: 'GAME',
    grade: null,
    name: '냉철한 분석',
    description: 'The Analyst로 클리어',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'CLEAR_WITH_ADVISOR', advisorId: 'analyst' },
  },
  {
    id: 'game_gambler',
    category: 'GAME',
    grade: null,
    name: '운명을 건다',
    description: 'The Gambler로 클리어',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'CLEAR_WITH_ADVISOR', advisorId: 'gambler' },
  },
  {
    id: 'game_over',
    category: 'GAME',
    grade: null,
    name: '첫 파산',
    description: '첫 게임 오버',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'GAME_OVER_ONCE' },
  },
  {
    id: 'game_phoenix',
    category: 'GAME',
    grade: null,
    name: '불사조',
    description: '체력 1 + 자본 음수 3턴에서 클리어',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'CLUTCH_CLEAR' },
  },
  {
    id: 'game_king',
    category: 'GAME',
    grade: null,
    name: 'S급 경영인',
    description: 'S등급 클리어',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'CLEAR_GRADE', grade: 'S' },
  },
  {
    id: 'game_legend',
    category: 'GAME',
    grade: null,
    name: '전설의 시작',
    description: 'Legend 등급 보상 획득',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'REWARD_GRADE', grade: 'LEGEND' },
  },
  {
    id: 'game_rival',
    category: 'GAME',
    grade: null,
    name: 'MONOPOL 정복',
    description: 'MONOPOL 라이벌 전원 파산시키기',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'ALL_RIVALS_BANKRUPT' },
  },
  {
    id: 'game_allin',
    category: 'GAME',
    grade: null,
    name: '올인',
    description: '말도안되는 선택 5번 연속 성공',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'ABSURD_STREAK', count: 5 },
  },
  {
    id: 'game_speed',
    category: 'GAME',
    grade: null,
    name: '스피드런',
    description: '30분 이내 클리어',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'CLEAR_UNDER_MINUTES', minutes: 30 },
  },
  {
    id: 'game_retry',
    category: 'GAME',
    grade: null,
    name: '오기',
    description: '게임 오버 후 재도전해서 클리어',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'RETRY_CLEAR' },
  },
  {
    id: 'game_perfect',
    category: 'GAME',
    grade: null,
    name: '완벽한 경영',
    description: 'S등급 + 신용점수 100 + 체력 만땅으로 클리어',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'PERFECT_CLEAR' },
  },
  {
    id: 'game_collector',
    category: 'GAME',
    grade: null,
    name: '수집가',
    description: 'MONOPOL 라이벌 도감 전부 채우기',
    icon: '/assets/logo_image-f7z3e97D.png',
    condition: { type: 'RIVAL_DEX_COMPLETE' },
  },
]
