export const ADVISORS = [
  {
    id: 'raider',
    name: 'The Raider',
    style: '공격형',
    passive: '공격 성장',
    description: '낮은 가격과 빠른 모멘텀으로 시장을 공격적으로 장악한다.',
    buffs: [
      '매력도 +7%',
      '모멘텀 상승속도 ×1.5',
      '라이벌보다 저가면 매력도 +5~10%',
    ],
    nerfs: ['최대 체력 8칸'],
    reportStyle: '점유율·가격경쟁력 중심',
    profileImage: '/assets/advisor_raider_profile-BG4Qmc-_.png',
    profileImageV2: '/assets/advisor_raider_v2-B08MoNtF.png',
    difficulty: 4,
    streakBonus: 3,
  },
  {
    id: 'guardian',
    name: 'The Guardian',
    style: '안정형',
    passive: '위험 방어',
    description: '리스크를 최소화하고 안정적인 경영을 추구한다.',
    buffs: [
      '체력 감소 -1',
      '이자율 -10%',
      '적자 시 체력 감소 확률 -20%',
    ],
    nerfs: ['발주량 -10%', '모멘텀 둔화 ×0.8'],
    reportStyle: '리스크·부채 위험도 중심',
    profileImage: '/assets/advisor_guardian_profile-DheSXB--.png',
    profileImageV2: '/assets/advisor_guardian_v2-DxuF_6Nw.png',
    difficulty: 2,
    streakBonus: 5,
  },
  {
    id: 'analyst',
    name: 'The Analyst',
    style: '분석형',
    passive: '정보 우위',
    description: '데이터를 분석해 최적의 판단을 내린다.',
    buffs: [
      '라이벌 정보 추가 공개',
      '경기 국면 전환 1턴 전 예고',
    ],
    nerfs: ['직접 수치 버프 없음'],
    reportStyle: '기여도% 원인 분석',
    profileImage: '/assets/advisor_analyst_profile-aFBaficW.png',
    profileImageV2: '/assets/advisor_analyst_v2-C9Ri7xK3.png',
    difficulty: 3,
    streakBonus: 4,
  },
  {
    id: 'gambler',
    name: 'The Gambler',
    style: '도박형',
    passive: '이벤트 한방',
    description: '확률에 모든 것을 건다. 고위험 고수익.',
    buffs: [
      '도박 확률 +15%',
      '이벤트 카드 2장 등장',
    ],
    nerfs: [
      '체력 자동회복 없음',
      '외부 이벤트 효과 ×1.3',
    ],
    reportStyle: '이벤트 결과 중심',
    profileImage: '/assets/advisor_gambler_profile-Mw_W8stF.png',
    profileImageV2: '/assets/advisor_gambler_v2-CRy4xqbA.png',
    difficulty: 5,
    streakBonus: 0,
  },
]
