export const MONOPOL_STAGES = [
  {
    id: 'stage_1',
    floorMin: 1,
    floorMax: 10,
    rival: 'junhyuk',
    rivalName: '준혁',
    company: '준혁상회',
    tier: 'ENTRY',
    capitalMultiplier: 0.3,
    specialAbility: null,
    marketIntervention: null,
    entryMessage: 'MONOPOL의 말단 준혁이 나타났다. 파산시켜라.',
    hint: '기본 전략을 익혀라. 가격과 발주량을 조정해보자.',
  },
  {
    id: 'stage_2',
    floorMin: 11,
    floorMax: 20,
    rival: 'sua',
    rivalName: '수아',
    company: 'SUA Works',
    tier: 'ENTRY',
    capitalMultiplier: 0.5,
    specialAbility: {
      type: 'MARKETING_BLITZ',
      interval: 3,
      effect: { awarenessBoost: 20 },
    },
    marketIntervention: {
      type: 'DEMAND_SUPPRESS',
      interval: 5,
      effect: { demandMultiplier: 0.9 },
      duration: 1,
    },
    entryMessage: '수아가 마케팅 폭격을 준비 중이다. 인지도로 맞서라.',
    hint: '가격을 바꾸면 어떤 일이 생길까요?',
  },
  {
    id: 'stage_3',
    floorMin: 21,
    floorMax: 40,
    rival: 'sungjin',
    rivalName: '성진',
    company: '성진인더스트리',
    tier: 'MID',
    capitalMultiplier: 0.8,
    specialAbility: {
      type: 'PRICE_DUMP',
      interval: 5,
      effect: { priceMultiplier: 0.7 },
      duration: 1,
    },
    marketIntervention: {
      type: 'SUPPLY_GLUT',
      interval: 5,
      effect: { demandMultiplier: 0.85 },
      duration: 2,
    },
    entryMessage: '성진이 가격을 확 낮춘다. 원가를 낮추거나 품질로 맞서라.',
    hint: '투자 전 기대값을 계산하세요.',
  },
  {
    id: 'stage_4',
    floorMin: 41,
    floorMax: 60,
    rival: 'jieun',
    rivalName: '지은',
    company: 'JE Solutions',
    tier: 'MID',
    capitalMultiplier: 1.0,
    specialAbility: {
      type: 'COST_REDUCTION_STACK',
      interval: 1,
      effect: { costReductionPerTurn: 0.005 },
    },
    marketIntervention: {
      type: 'RAW_MATERIAL_MONOPOLY',
      interval: 5,
      effect: { costMultiplier: 1.1 },
      duration: 2,
    },
    entryMessage: '지은은 조용히 원가를 줄이고 있다. 더 빠르게 절감하라.',
    hint: '지은보다 빠르게 원가를 절감하라.',
  },
  {
    id: 'stage_5',
    floorMin: 61,
    floorMax: 80,
    rival: 'junseo',
    rivalName: '준서',
    company: 'JUNSEO Group',
    tier: 'SENIOR',
    capitalMultiplier: 1.5,
    specialAbility: {
      type: 'QUALITY_RUSH',
      interval: 3,
      effect: { qualityBoost: 5 },
    },
    marketIntervention: {
      type: 'ECONOMY_SUPPRESS',
      interval: 3,
      effect: { forcePhaseDown: 1 },
      duration: 1,
    },
    entryMessage: '준서가 품질을 올리고 있다. 차별화 전략이 필요하다.',
    hint: '불황엔 가격, 호황엔 품질로 승부하라.',
  },
  {
    id: 'stage_6',
    floorMin: 81,
    floorMax: 95,
    rival: 'seoyeon',
    rivalName: '서연',
    company: 'Seo & Partners',
    tier: 'SENIOR',
    capitalMultiplier: 2.0,
    specialAbility: {
      type: 'BRAND_INVEST',
      interval: 1,
      effect: { brandBoost: 0.2 },
    },
    marketIntervention: {
      type: 'CONSUMER_MANIPULATION',
      interval: 3,
      effect: { brandConsumerRatio: 0.2 },
      duration: 2,
    },
    entryMessage: '서연은 브랜드로 소비자를 끌어들인다. 마케팅 전략을 세워라.',
    hint: '브랜드가 높으면 인지도 최대치가 올라간다.',
  },
  {
    id: 'stage_7',
    floorMin: 96,
    floorMax: 110,
    rival: 'taejun',
    rivalName: '태준',
    company: '태준홀딩스',
    tier: 'SENIOR',
    capitalMultiplier: 2.0,
    specialAbility: {
      type: 'PHASE_OPTIMIZER',
      interval: 1,
      effect: { optimalStrategyPerPhase: true },
    },
    marketIntervention: {
      type: 'PHASE_CHAOS',
      interval: 3,
      effect: { randomPhaseShift: true },
      duration: 1,
    },
    entryMessage: '태준은 경기를 읽는다. 국면 변화에 더 빠르게 대응하라.',
    hint: '경기 국면이 바뀌면 소비자 행동도 바뀐다.',
  },
  {
    id: 'stage_8',
    floorMin: 111,
    floorMax: 118,
    rival: 'cheolmin',
    rivalName: '철민',
    company: 'CHEOLMIN Corp',
    tier: 'CHAMPION',
    capitalMultiplier: 3.0,
    specialAbility: {
      type: 'EVENT_AMPLIFY',
      interval: 1,
      effect: { eventIntensityMultiplier: 1.5 },
    },
    marketIntervention: {
      type: 'FORCE_EXTERNAL_EVENT',
      interval: 1,
      effect: { forceExternalEvent: true },
      duration: 1,
    },
    entryMessage: '철민이 시장을 흔들고 있다. 현금을 지켜라.',
    hint: '외부 충격에 대비해 현금 여유를 확보하라.',
  },
  {
    id: 'stage_9',
    floorMin: 119,
    floorMax: 119,
    rival: 'dogan',
    rivalName: '도건',
    company: '도건그룹',
    tier: 'CHAMPION',
    capitalMultiplier: 2.5,
    specialAbility: {
      type: 'COMBINED',
      description: '준서 + 철민 능력 동시',
    },
    marketIntervention: {
      type: 'COMBINED',
      description: '경기 하향 + 외부 이벤트 강제 동시',
    },
    entryMessage: '도건. MONOPOL의 부보스다. 모든 걸 써야 한다.',
    hint: '지금까지 배운 모든 전략을 동원하라.',
  },
  {
    id: 'stage_boss',
    floorMin: 120,
    floorMax: 120,
    rival: 'hyekyung',
    rivalName: '혜경',
    company: 'HK International',
    tier: 'BOSS',
    capitalMultiplier: Infinity,
    specialAbility: {
      type: 'AI_COUNTER',
      description: '매 턴 플레이어 전략 분석 후 최적 카운터',
    },
    marketIntervention: {
      type: 'FULL_CONTROL',
      description: '경기 국면 완전 장악',
    },
    bossCondition: {
      type: 'SHARE_SUPPRESSION',
      targetShareBelow: 0.5,
      requiredTurns: 3,
    },
    entryMessage: '혜경. MONOPOL의 수장. 3턴 연속 압도하면 끝난다.',
    hint: '같은 전략을 2턴 연속 쓰면 혜경이 카운터한다.',
  },
]

export function getCurrentStage(floor) {
  return MONOPOL_STAGES.find(
    stage => floor >= stage.floorMin && floor <= stage.floorMax,
  ) || null
}

export function isNewStage(prevFloor, currentFloor) {
  const prev = getCurrentStage(prevFloor)
  const current = getCurrentStage(currentFloor)
  if (!prev || !current) return false
  return prev.id !== current.id
}

export function isBossStage(floor) {
  return floor === 120
}
