export const RIVALS = [
  {
    id: 'junhyuk',
    name: '준혁',
    company: '준혁상회',
    tier: 'ENTRY',
    monopolMember: true,
    monopolRank: 'ENTRY',
    monopolStageId: 'stage_1',
    profileImage: '/assets/rival_entry_junhyuk-CHlAhbxg.png',
    floorUnlock: 1,
    stats: { quality: 5.0, brand: 1, awareness: 8 },
    baseStrategy: {
      priceMultiplier: 1.1,
      orderMultiplier: 0.8,
      marketingBudget: 'LOW',
    },
    dialogue: {
      appear: '나도 이제 사장이야! 두고 봐!',
      bankrupt: '말이 안 돼... 겨우 3개월인데...',
    },
  },
  {
    id: 'sua',
    name: '수아',
    company: 'SUA Works',
    tier: 'ENTRY',
    monopolMember: true,
    monopolRank: 'ENTRY',
    monopolStageId: 'stage_2',
    profileImage: '/assets/rival_entry_sua-Ng4BiHAI.png',
    floorUnlock: 11,
    stats: { quality: 5.5, brand: 2, awareness: 15 },
    baseStrategy: {
      priceMultiplier: 1.2,
      orderMultiplier: 0.9,
      marketingBudget: 'MID',
    },
    dialogue: {
      appear: '알바비 모아서 여기까지 왔어. 절대 안 져.',
      bankrupt: '결국 이렇게 되는 건가...',
    },
  },
  {
    id: 'sungjin',
    name: '성진',
    company: '성진인더스트리',
    tier: 'MID',
    monopolMember: true,
    monopolRank: 'MID',
    monopolStageId: 'stage_3',
    profileImage: '/assets/rival_mid_sungjin-D6YbcSZf.png',
    floorUnlock: 21,
    stats: { quality: 6.0, brand: 3, awareness: 20 },
    baseStrategy: {
      priceMultiplier: 1.4,
      orderMultiplier: 1.0,
      marketingBudget: 'MID',
    },
    dialogue: {
      appear: '대기업은 나한테 안 맞아. 내 방식으로 간다.',
      bankrupt: '시장이 이렇게 돌아가는 거였군.',
    },
  },
  {
    id: 'jieun',
    name: '지은',
    company: 'JE Solutions',
    tier: 'MID',
    monopolMember: true,
    monopolRank: 'MID',
    monopolStageId: 'stage_4',
    profileImage: '/assets/rival_mid_jieun-BOpsHoqL.png',
    floorUnlock: 41,
    stats: { quality: 6.5, brand: 3, awareness: 25 },
    baseStrategy: {
      priceMultiplier: 1.5,
      orderMultiplier: 1.0,
      marketingBudget: 'MID',
    },
    dialogue: {
      appear: '...',
      bankrupt: '예상 못 한 변수였어.',
    },
  },
  {
    id: 'junseo',
    name: '준서',
    company: 'JUNSEO Group',
    tier: 'SENIOR',
    monopolMember: true,
    monopolRank: 'SENIOR',
    monopolStageId: 'stage_5',
    profileImage: '/assets/rival_senior_junseo-D7JBRjRD.png',
    floorUnlock: 61,
    stats: { quality: 8.0, brand: 5, awareness: 45 },
    baseStrategy: {
      priceMultiplier: 1.8,
      orderMultiplier: 1.2,
      marketingBudget: 'HIGH',
    },
    dialogue: {
      appear: '재미있겠네. 네 회사 어디 한번 보자.',
      bankrupt: '...인정한다.',
    },
  },
  {
    id: 'seoyeon',
    name: '서연',
    company: 'Seo & Partners',
    tier: 'SENIOR',
    monopolMember: true,
    monopolRank: 'SENIOR',
    monopolStageId: 'stage_6',
    profileImage: '/assets/rival_senior_seoyeon-DQw87pvW.png',
    floorUnlock: 81,
    stats: { quality: 8.5, brand: 7, awareness: 55 },
    baseStrategy: {
      priceMultiplier: 2.0,
      orderMultiplier: 1.1,
      marketingBudget: 'HIGH',
    },
    dialogue: {
      appear: '브랜드가 전부야. 당신은 아직 모르는 것 같지만.',
      bankrupt: '브랜드도 결국 사람이 만드는 거였네.',
    },
  },
  {
    id: 'taejun',
    name: '태준',
    company: '태준홀딩스',
    tier: 'SENIOR',
    monopolMember: true,
    monopolRank: 'SENIOR',
    monopolStageId: 'stage_7',
    profileImage: '/assets/rival_senior_taejun-NZJ6-s3M.png',
    floorUnlock: 96,
    stats: { quality: 9.0, brand: 6, awareness: 60 },
    baseStrategy: {
      priceMultiplier: 1.9,
      orderMultiplier: 1.3,
      marketingBudget: 'HIGH',
    },
    dialogue: {
      appear: '경기를 읽는 자가 시장을 지배한다.',
      bankrupt: '이번엔 내가 잘못 읽었군.',
    },
  },
  {
    id: 'cheolmin',
    name: '철민',
    company: 'CHEOLMIN Corp',
    tier: 'CHAMPION',
    monopolMember: true,
    monopolRank: 'CHAMPION',
    monopolStageId: 'stage_8',
    profileImage: '/assets/rival_champion_cheolmin-DQI-_sih.png',
    floorUnlock: 111,
    stats: { quality: 10.0, brand: 8, awareness: 75 },
    baseStrategy: {
      priceMultiplier: 2.2,
      orderMultiplier: 1.5,
      marketingBudget: 'MAX',
    },
    dialogue: {
      appear: '시장을 흔드는 건 나야.',
      bankrupt: '...네가 이기는군.',
    },
  },
  {
    id: 'dogan',
    name: '도건',
    company: '도건그룹',
    tier: 'CHAMPION',
    monopolMember: true,
    monopolRank: 'VICE_BOSS',
    monopolStageId: 'stage_9',
    profileImage: '/assets/rival_champion_dogeon-BRN0GlPx.png',
    floorUnlock: 119,
    stats: { quality: 11.0, brand: 9, awareness: 80 },
    baseStrategy: {
      priceMultiplier: 2.5,
      orderMultiplier: 1.5,
      marketingBudget: 'MAX',
    },
    dialogue: {
      appear: '혜경 회장님을 만나려면 나를 먼저 지나가야 해.',
      bankrupt: '...대단하군. 혜경 회장님을 직접 만나봐.',
    },
  },
  {
    id: 'hyekyung',
    name: '혜경',
    company: 'HK International',
    tier: 'BOSS',
    monopolMember: true,
    monopolRank: 'BOSS',
    monopolStageId: 'stage_boss',
    profileImage: '/assets/rival_champion_hyegyeong-Cuy8B_O2.png',
    floorUnlock: 120,
    stats: { quality: 15.0, brand: 10, awareness: 90 },
    baseStrategy: {
      priceMultiplier: 3.0,
      orderMultiplier: 2.0,
      marketingBudget: 'MAX',
    },
    dialogue: {
      appear: '시장은 내가 만드는 거야. 네가 아무리 잘해도 내가 흔들면 끝이야.',
      counter: '패턴을 읽었어. 그걸로는 안 돼.',
      losing: '...흥미롭군.',
      bankrupt: '시장은 결국 사람이 만드는 게 아니었나.',
    },
  },
]
