export const EXTERNAL_EVENTS = [
  {
    id: 'E01',
    title: '금리 인상',
    category: 'FINANCE',
    description: '중앙은행이 기준금리를 인상했다. 대출 이자 부담이 커진다.',
    effect: {
      interestRateChange: 0.015,
      creditScoreChange: -2,
      duration: 3,
      source: 'EXTERNAL',
    },
    backgroundImage: '/assets/bg_phase_contraction-CbRrs-qy.jpg',
  },
  {
    id: 'E02',
    title: '금리 인하',
    category: 'FINANCE',
    description: '중앙은행이 기준금리를 인하했다. 대출 조건이 완화된다.',
    effect: {
      interestRateChange: -0.01,
      duration: 3,
      source: 'EXTERNAL',
    },
    backgroundImage: '/assets/bg_phase_growth-BN5UHyVn.jpg',
  },
  {
    id: 'E03',
    title: '환율 폭등',
    category: 'FINANCE',
    description: '원달러 환율이 급등하며 수입 원자재 비용이 올랐다.',
    effect: {
      costMultiplier: 1.15,
      duration: 2,
      source: 'EXTERNAL',
    },
    backgroundImage: '/assets/bg_phase_contraction-CbRrs-qy.jpg',
  },
  {
    id: 'E04',
    title: '원자재 폭등',
    category: 'SUPPLY',
    description: '국제 원자재 가격이 급등했다. 생산 원가가 크게 오른다.',
    effect: {
      costMultiplier: 1.20,
      duration: 2,
      source: 'EXTERNAL',
    },
    backgroundImage: '/assets/bg_phase_recession-CCyrxX4k.jpg',
  },
  {
    id: 'E05',
    title: '원자재 폭락',
    category: 'SUPPLY',
    description: '국제 원자재 가격이 급락했다. 생산 원가가 낮아진다.',
    effect: {
      costMultiplier: 0.85,
      duration: 2,
      source: 'EXTERNAL',
    },
    backgroundImage: '/assets/bg_phase_growth-BN5UHyVn.jpg',
  },
  {
    id: 'E06',
    title: '소비 심리 위축',
    category: 'DEMAND',
    description: '경기 불안으로 소비자들이 지갑을 닫기 시작했다.',
    effect: {
      demandMultiplier: 0.80,
      duration: 2,
      source: 'EXTERNAL',
    },
    backgroundImage: '/assets/bg_phase_contraction-CbRrs-qy.jpg',
  },
  {
    id: 'E07',
    title: '소비 심리 회복',
    category: 'DEMAND',
    description: '경기 회복 기대감으로 소비자 지출이 늘어나고 있다.',
    effect: {
      demandMultiplier: 1.20,
      duration: 2,
      source: 'EXTERNAL',
    },
    backgroundImage: '/assets/bg_phase_growth-BN5UHyVn.jpg',
  },
  {
    id: 'E08',
    title: '경기 부양책 발표',
    category: 'POLICY',
    description: '정부가 대규모 경기 부양책을 발표했다. 시장 전반이 활기를 띤다.',
    effect: {
      demandMultiplier: 1.15,
      forcePhase: 'growth',
      duration: 3,
      source: 'EXTERNAL',
    },
    backgroundImage: '/assets/bg_phase_boom-BqFLGgpW.jpg',
  },
  {
    id: 'E09',
    title: '긴축 정책 발표',
    category: 'POLICY',
    description: '정부가 긴축 재정 정책을 발표했다. 시장이 냉각된다.',
    effect: {
      demandMultiplier: 0.85,
      forcePhase: 'contraction',
      duration: 2,
      source: 'EXTERNAL',
    },
    backgroundImage: '/assets/bg_phase_contraction-CbRrs-qy.jpg',
  },
  {
    id: 'E10',
    title: '전염병 확산',
    category: 'CRISIS',
    description: '전염병이 확산되며 소비와 생산 모두 타격을 받고 있다.',
    effect: {
      demandMultiplier: 0.70,
      costMultiplier: 1.10,
      forcePhase: 'recession',
      duration: 3,
      source: 'EXTERNAL',
    },
    backgroundImage: '/assets/bg_phase_recession-CCyrxX4k.jpg',
  },
]
