export const EXTERNAL_EVENTS = [
  {
    id: 'E01',
    title: '금리 인상',
    category: 'FINANCE',
    description: '중앙은행이 기준금리를 인상했다.',
    effect: {
      interestRateChange: 0.015,
      creditScoreChange: -2,
      duration: 3,
    },
    backgroundImage: '/assets/images/backgrounds/event_finance.png',
  },
  {
    id: 'E02',
    title: '금리 인하',
    category: 'FINANCE',
    description: '중앙은행이 기준금리를 인하했다.',
    effect: {
      interestRateChange: -0.01,
      duration: 3,
    },
    backgroundImage: '/assets/images/backgrounds/event_finance.png',
  },
  {
    id: 'E03',
    title: '환율 폭등',
    category: 'FINANCE',
    description: '원화 가치가 급락해 수입 원자재 비용이 늘었다.',
    effect: {
      costMultiplier: 1.15,
      duration: 2,
    },
    backgroundImage: '/assets/images/backgrounds/event_finance.png',
  },
  {
    id: 'E04',
    title: '주식시장 폭락',
    category: 'FINANCE',
    description: '증시 급락으로 소비 심리가 얼어붙었다.',
    effect: {
      forcePhase: 'contraction',
      duration: 1,
    },
    backgroundImage: '/assets/images/backgrounds/event_crisis.png',
  },
  {
    id: 'E05',
    title: '소비 진작 정책',
    category: 'FINANCE',
    description: '정부가 소비 진작 패키지를 발표했다.',
    effect: {
      forcePhase: 'growth',
      demandMultiplier: 1.15,
      duration: 2,
    },
    backgroundImage: '/assets/images/backgrounds/event_policy.png',
  },
  {
    id: 'E06',
    title: '유조선 침몰',
    category: 'SUPPLY',
    description: '주요 항로에서 유조선이 침몰해 운송비가 급등했다.',
    effect: {
      costMultiplier: 1.25,
      orderCapMultiplier: 0.8,
      duration: 3,
    },
    backgroundImage: '/assets/images/backgrounds/event_supply.png',
  },
  {
    id: 'E07',
    title: '원자재 폭등',
    category: 'SUPPLY',
    description: '핵심 원자재 가격이 급등했다.',
    effect: {
      costMultiplier: 1.20,
      duration: 2,
    },
    backgroundImage: '/assets/images/backgrounds/event_supply.png',
  },
  {
    id: 'E08',
    title: '원자재 폭락',
    category: 'SUPPLY',
    description: '원자재 가격이 급락해 원가가 낮아졌다.',
    effect: {
      costMultiplier: 0.85,
      duration: 2,
    },
    backgroundImage: '/assets/images/backgrounds/event_supply.png',
  },
  {
    id: 'E09',
    title: '항만 파업',
    category: 'SUPPLY',
    description: '항만 노조 파업으로 물류가 마비됐다.',
    effect: {
      orderCapMultiplier: 0.7,
      costMultiplier: 1.10,
      duration: 2,
    },
    backgroundImage: '/assets/images/backgrounds/event_supply.png',
  },
  {
    id: 'E10',
    title: '공급망 정상화',
    category: 'SUPPLY',
    description: '글로벌 공급망이 회복돼 원가가 낮아졌다.',
    effect: {
      costMultiplier: 0.90,
      duration: 2,
    },
    backgroundImage: '/assets/images/backgrounds/event_supply.png',
  },
  {
    id: 'E11',
    title: '전쟁 발발',
    category: 'CRISIS',
    description: '주요 교역국에서 전쟁이 발발했다.',
    effect: {
      forcePhase: 'recession',
      costMultiplier: 1.30,
      demandMultiplier: 0.85,
      duration: 4,
    },
    backgroundImage: '/assets/images/backgrounds/event_war.png',
  },
  {
    id: 'E12',
    title: '전쟁 종식',
    category: 'CRISIS',
    description: '전쟁이 끝나고 경제가 회복세로 돌아섰다.',
    effect: {
      forcePhase: 'stable',
      duration: 1,
    },
    backgroundImage: '/assets/images/backgrounds/event_peace.png',
  },
  {
    id: 'E13',
    title: '대규모 자연재해',
    category: 'CRISIS',
    description: '대형 재해로 소비가 급감했다.',
    effect: {
      forcePhase: 'contraction',
      demandMultiplier: 0.80,
      duration: 2,
    },
    backgroundImage: '/assets/images/backgrounds/event_disaster.png',
  },
  {
    id: 'E14',
    title: '전염병 확산',
    category: 'CRISIS',
    description: '전염병이 확산되며 소비 활동이 위축됐다.',
    effect: {
      forcePhase: 'contraction',
      demandMultiplier: 0.75,
      duration: 3,
    },
    backgroundImage: '/assets/images/backgrounds/event_pandemic.png',
  },
  {
    id: 'E15',
    title: '대규모 파업',
    category: 'CRISIS',
    description: '전국적인 파업으로 생산 차질이 생겼다.',
    effect: {
      orderCapMultiplier: 0.75,
      duration: 2,
    },
    backgroundImage: '/assets/images/backgrounds/event_strike.png',
  },
  {
    id: 'E16',
    title: '소비 트렌드 변화',
    category: 'TREND',
    description: '소비자 트렌드가 바뀌어 품질 중시 소비자가 늘었다.',
    effect: {
      consumerRatioShift: { quality: 0.10, price: -0.10 },
      duration: 3,
    },
    backgroundImage: '/assets/images/backgrounds/event_trend.png',
  },
  {
    id: 'E17',
    title: '친환경 규제 강화',
    category: 'TREND',
    description: '환경 규제 강화로 원가가 상승했다.',
    effect: {
      costMultiplier: 1.15,
      duration: 4,
    },
    backgroundImage: '/assets/images/backgrounds/event_policy.png',
  },
  {
    id: 'E18',
    title: '세금 인하',
    category: 'TREND',
    description: '법인세 인하로 순이익이 개선됐다.',
    effect: {
      netProfitMultiplier: 1.10,
      duration: 3,
    },
    backgroundImage: '/assets/images/backgrounds/event_policy.png',
  },
  {
    id: 'E19',
    title: '기술 혁신 붐',
    category: 'TREND',
    description: '기술 혁신 붐으로 시장 전체 수요가 증가했다.',
    effect: {
      demandMultiplier: 1.15,
      duration: 2,
    },
    backgroundImage: '/assets/images/backgrounds/event_trend.png',
  },
  {
    id: 'E20',
    title: '경기 회복 뉴스',
    category: 'TREND',
    description: '경기 회복 신호가 나타나며 소비 심리가 살아났다.',
    effect: {
      forcePhase: 'growth',
      duration: 1,
    },
    backgroundImage: '/assets/images/backgrounds/event_trend.png',
  },
]
